import mongoengine as me

class Intervenants(me.Document):
    meta = {'collection': 'intervenants', 'strict': False}
    # mapping from db
    email = me.StringField()
    volontaire = me.StringField()
    hesitations = me.StringField()
    contact1 = me.StringField()
    contact2 = me.StringField()
    aider = me.StringField()
    voyager = me.StringField()
    travailler_en_equipe = me.StringField()
    soutenir = me.StringField()
    connaitre_personnes_cultures = me.StringField()
    mettre_a_dispotion = me.StringField()
    responsabilites = me.StringField()
    actif = me.StringField()
    autres_facteurs = me.StringField()
    secteurs = me.StringField()
    domaines_1 = me.StringField()
    domaines_2 = me.StringField()
    fonctions = me.StringField()
    competences = me.StringField()
    complements =me.StringField()
    dispo = me.StringField()
    duree =  me.StringField()
    deplacements_par_an = me.StringField()
    langue_maternelle = me.StringField()
    notions = me.StringField()
    lu_parle_ecrit = me.StringField()
    autonomes = me.StringField()
    roles = me.StringField()
    exp_inter_oui_non = me.StringField()
    exp_pro = me.StringField()
    exp_benevole = me.StringField()
    connaissances_structure = me.StringField()
    suggestions = me.StringField()
    delegation = me.StringField()
    idees= me.StringField()
